[build-system]
requires = [
    "read_version ~= 0.2.0",
    "setuptools >= 42.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.read_version]
version = "src.wheel_inspect.__init__:__version__"
